name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GIT_TRACE: 1
  GIT_CURL_VERBOSE: 1
  TOKEN: ${{ secrets.GIT_TOKEN}}

jobs:
  print_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          for secret in $(env | grep '^SECRET_' | cut -d= -f1); do
            echo "Secret Name: $secret"
            echo "Secret Value: ${!secret}"
          done
#        retention-days: 1

#  install-gradle:
#    name: Install gradle
#    runs-on: ubuntu-latest
#    steps:
#      - name: Update the package index
#        run: sudo apt update
#
#      - name: Install gradle
#        run: sudo apt install -y gradle
#
#      - name: Verify the installation by checking the Gradle version
#        run: gradle --version

  build:
    name: Gradle build
#    needs: install-gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
#        server-username: ${{ secrets.USERNAME_GITHUB || github.token }}
#        server-password: ${{ secrets.TOKEN_GITHUB || github.token }}
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Present Working directory
        run: ls -la

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
